local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xyrozz764/Traitor-hub/main/Init.lua"))()
local Window = Library:CreateLib("Tutorial", "BloodTheme")
local Tab = Window:NewTab("Click")
local Section = Tab:NewSection("Click")
Section:NewLabel("Click")
Section:NewButton("Click", "Just click", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/xyrozz764/Traitor-hub/main/Init.lua"))()
end)
